[package]
name = "update_notifier"
version = "0.1.0"
authors = []

[dependencies.hyper]
version = "0.11"

[dependencies.tokio-core]
version = "*"

[dependencies.futures]
version = "*"

[lib]
name = "update_notifier"
crate-type = ["staticlib"]
