name: Build and Run Chimera

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up MinGW32
      uses: corretto/setup-mingw@v1
      with:
        arch: x86
        threads: posix
        exceptions: sjlj
        addToPath: true

    - name: Run build.bat
      shell: cmd
      run: |
        cd client\lua\lua
        call ..\..\..\build.bat
        cd ..\..\..

    - name: Display build results
      run: |
        type client\lua\lua\bin\liblua.a
        dir bin /s /b
